version: '3.8'

services:

  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/front'
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=https://murmuring-beyond-76885.herokuapp.com

